### ISSUE TITLE
2 humans and 2 AI freezes after AI declares trump

### ISSUE THREAD

**Issue by antequ** [ytung/tractor#1]
Another minor corner case! (very low priority)
When playing a game with 2 humans and 2 AI, if the AI declares a card first, after all cards are dealt, there is no way to pass, and no way to declare. The screen just asks to declare (there is no option to pass) but you can't declare anything, even if you have 2 of a kind. This scenario does not happen with 1 human and 3 AI, but it happens repeatedly with 2 humans and 2 AI. 

Set up: Two humans, 2 computers, tractor (not find a friend) version with 2 decks. Humans can be on the same team or opposite teams.
Human 1 POV:
![image](https://user-images.githubusercontent.com/7333308/80318929-60766b00-87c2-11ea-9849-dc854b2dc172.png)

Human 2 POV:
![image](https://user-images.githubusercontent.com/7333308/80318939-6ec48700-87c2-11ea-85d7-986c957eb40b.png)

**Comment by kevinychen** [comment]
Saving relevant logs so that future Kevin can debug
```
2020-04-26T20:31:54.305388+00:00 app[web.1]: IncomingMessage.DeclareRequest(cardIds=[178])
2020-04-26T20:31:59.471060+00:00 app[web.1]: WARN  [2020-04-26 20:31:59,470] org.atmosphere.cpr.DefaultBroadcaster: This message Entry{message={"DRAW":{"status":"DRAW","currentPlayerIndex":0,"deck":[169,164,186,122,107,134,129,167,170,104,147,158],"playerHands":{"62c0c7cf-b71a-4e1c-8575-c11ef3f939ed":[130,139,201,197,144,156,194,207,108,187,132,208,205,183,175,120,125,145,160,114,200,152,178,148],"95003207-f334-42e7-86d8-bc5ba4ad984a":[161,172,155,204,121,192,116,157,153,176,136,177,133,131,119,118,191,184,159,195,127,193,123,150],"1c426440-ced6-4a77-98b5-65bace5b5c0f":[206,126,135,165,110,171,109,117,166,142,106,146,188,182,196,141,137,103,102,190,105,173,113,128],"be4a299c-f234-466b-b44b-7466c1dd1676":[138,180,185,101,149,124,168,174,115,151,198,140,181,203,199,163,143,179,112,154,111,189,162,202]}}}, type=ALL, future=org.atmosphere.cpr.BroadcasterFuture@3edf4ead} will be lost
2020-04-26T20:31:59.471248+00:00 app[web.1]: WARN  [2020-04-26 20:31:59,470] org.atmosphere.cpr.DefaultBroadcaster: Failed to submit broadcast handler runnable to for Broadcaster/tractor/GZGX
2020-04-26T20:31:59.471249+00:00 app[web.1]: ! java.lang.OutOfMemoryError: unable to create new native thread
2020-04-26T20:31:59.471250+00:00 app[web.1]: ! at java.lang.Thread.start0(Native Method)
2020-04-26T20:31:59.471250+00:00 app[web.1]: ! at java.lang.Thread.start(Thread.java:717)
2020-04-26T20:31:59.471251+00:00 app[web.1]: ! at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
2020-04-26T20:31:59.471251+00:00 app[web.1]: ! at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367)
2020-04-26T20:31:59.471251+00:00 app[web.1]: ! at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
2020-04-26T20:31:59.471252+00:00 app[web.1]: ! at org.atmosphere.cpr.DefaultBroadcaster.queueWriteIO(DefaultBroadcaster.java:775)
2020-04-26T20:31:59.471252+00:00 app[web.1]: ! at org.atmosphere.cpr.DefaultBroadcaster.deliverPush(DefaultBroadcaster.java:687)
2020-04-26T20:31:59.471253+00:00 app[web.1]: ! at org.atmosphere.cpr.DefaultBroadcaster.push(DefaultBroadcaster.java:569)
2020-04-26T20:31:59.471253+00:00 app[web.1]: ! at org.atmosphere.cpr.DefaultBroadcaster$1.run(DefaultBroadcaster.java:422)
2020-04-26T20:31:59.471253+00:00 app[web.1]: ! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-04-26T20:31:59.471254+00:00 app[web.1]: ! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-26T20:31:59.471255+00:00 app[web.1]: ! at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
2020-04-26T20:31:59.471255+00:00 app[web.1]: ! at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2020-04-26T20:31:59.471255+00:00 app[web.1]: ! at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
2020-04-26T20:31:59.471256+00:00 app[web.1]: ! at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2020-04-26T20:31:59.471256+00:00 app[web.1]: ! at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

@FutureKevin: investigate whether there's a memory leak or whether the Heroku instance doesn't have enough resources.
